<!--
    THIS FILE WAS AUTOMATICALLY GENERATED BY GODOT HTML5 EXPORT USING CUSTOM SHELL.
    https://docs.godotengine.org/en/stable/tutorials/platform/customizing_html5_shell.html
-->

<canvas id="companion-canvas"></canvas>


<!-- svelte-ignore missing-declaration -->
<script lang="ts">
    import "./Companion.js";
    import { onMount } from "svelte";

    const executable = "Companion.js".slice(0, -3);

    const wasmPath = `/${executable}.wasm`;
    const pckPath = `/${executable}.pck`;

    onMount(() => {

        const companionCanvas = document.getElementById("companion-canvas");
        
        // @ts-ignore
        const engine = new Engine({"args":[],"canvasResizePolicy":2,"executable":"Companion","experimentalVK":false,"fileSizes":{"Companion.pck":24960,"Companion.wasm":26058406},"focusCanvas":true,"gdnativeLibs":[]});

        Promise.all([
            // Load and init the engine
            engine.init(wasmPath),
            // And the pck concurrently
            engine.preloadFile(pckPath),
        ]).then(() => {
            // Now start the engine.
            return engine.start({
                canvas: companionCanvas,
                args: ['--main-pack', pckPath],
                onProgress: (current: number, total: number) => {console.log(`${current}/${total}`)}
            });
        }).then(() => {
            console.log('Engine has started!');
        });

    });

</script>


